### ISSUE TITLE
Custom Xray config

### ISSUE THREAD

**Issue by Jds548** [YukidouSatoru/sphia#3]
Please add support for Custom Xray json config.

**Comment by YukidouSatoru** [comment]
After two rounds of refactoring, there are still quite a few bugs. We’ll add this feature once it’s stable.

**Comment by YukidouSatoru** [comment]
Try the [latest build](https://github.com/YukidouSatoru/sphia/actions/runs/9209360383).

**Comment by Jds548** [comment]
Thanks!
not working and usually export this error:
`Failed to start core: Exception: Local server is not available`
Dashboard also not showing any activity.
both regular VLESS and fragmented configs didn't work.

Fragment configs only works with Xray-core. Using [this tool](https://fragment.github1.cloud/) allows to generate custom fragment json from regular VLESS/VMESS/TROJAN configuration. The main reason to use custom configs is features like fragment.

**Comment by YukidouSatoru** [comment]
> Failed to start core: Exception: Local server is not available

It is likely because you did not provide a complete configuration that includes inbounds, or you did not correctly specify the HTTP port when adding the Custom Config Server, or the HTTP inbound in the configuration file has authentication enabled, leading to an error when Sphia tries to detect ports. If you do not want Sphia to access your proxy (such as obtaining IP through the proxy, updating the core, or setting the system proxy), you can set the value to -1, which will also disable the local server availability check.


> Dashboard also not showing any activity.

When running a custom configuration, Sphia cannot obtain statistics through the API, and the rule group switching function is also disabled. Because this feature is still in testing, API support may be considered in the future.

If you have more information or thoughts to share, please let us know.

**Comment by Jds548** [comment]
Thanks for your response and efforts! The Problem solved.
The custom config that I've been using also, had Routing Rules which I suspect that caused problem. After deleting rules and setting ports, it works now.
